version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/dev"
    schedule:
      interval: "daily"
    assignees:
      - "luisa-beerboom"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "luisa-beerboom"
