FROM postgres:17

# Install the postgresql debugger
RUN apt-get update
RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y --no-install-recommends postgresql-17-pldebugger

EXPOSE 5432
