# join_models_yml.py is a temporary script to create the old models.yml until
# all services are able to work with the new separat collections.

from pathlib import Path

import yaml


def build_models_yaml_content(meta_file: str, collections_dir: str) -> bytes:
    result = {}

    with open(meta_file, encoding="utf-8") as f:
        meta_data = yaml.safe_load(f)
        result["_meta"] = meta_data

    collections_path = Path(collections_dir)
    yaml_files = sorted(collections_path.glob("*.yml"))

    for yaml_file in yaml_files:
        with open(yaml_file, encoding="utf-8") as f:
            data = yaml.safe_load(f)

            result[yaml_file.stem] = data

    header = (
        "# GENERATED FILE - DO NOT EDIT MANUALLY\n"
        "# This file is automatically generated. Manual changes will be overwritten.\n"
        "---\n"
    )

    yaml_body = yaml.dump(
        result,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
    )

    return (header + yaml_body).encode("utf-8")


def join_yaml_file(meta_file: str, collections_dir: str, output_file: str) -> None:
    content = build_models_yaml_content(meta_file, collections_dir)

    with open(output_file, "wb") as f:
        f.write(content)


if __name__ == "__main__":
    SCRIPT_DIR = Path(__file__).resolve().parent.parent  # dev/
    PROJECT_ROOT = SCRIPT_DIR.parent

    meta_file = PROJECT_ROOT / "collection-meta.yml"
    collections_dir = PROJECT_ROOT / "collections"
    output_file = PROJECT_ROOT / "models.yml"
    try:
        join_yaml_file(str(meta_file), str(collections_dir), str(output_file))
    except Exception as e:
        print(f"Fehler: {e}")
