name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - 'feature/**'

env:
  PYTHON_VERSION: 3.10.x

jobs:
  validate-models:
    name: Validate models.yml
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install requirements
      run: pip install -r models_validator/requirements.txt

    - name: Validate models.yml
      run: python models_validator/validate.py models.yml
